# Generated by Django 6.1 on 2026-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=280)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('django', 'Django'), ('productivity', 'Productivity'), ('learning', 'Learning'), ('project', 'Project Notes')], default='learning', max_length=32)),
                ('emoji', models.CharField(default='📝', max_length=8)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
