# Generated by Django 6.1 on 2026-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
