# Generated by Django 6.1 on 2026-08-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='When this task is completed, the next one is created automatically.', max_length=16),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_until',
            field=models.DateField(blank=True, help_text='Optional. Stop creating new occurrences after this date.', null=True, verbose_name='Repeat until'),
        ),
    ]
