# Generated by Django 6.1 on 2026-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_recurrence_todo_recurrence_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Shows on every matching day in the calendar. Completing it creates the next occurrence.', max_length=16),
        ),
    ]
